// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Servo_Control

#include "ui.h"
int angle_changed = 0;

void Slider_Angle(lv_event_t * e)
{
	int angle_val = 0;
  angle_val = lv_slider_get_value(ui_Slider_Servo);
  lv_arc_set_value(ui_Arc_Servo ,angle_val);
  angle_changed = 1;
}

void Arc_Angle(lv_event_t * e)
{
	int angle_val = 0;
  angle_val = lv_arc_get_value(ui_Arc_Servo);
  lv_slider_set_value(ui_Slider_Servo ,angle_val, LV_ANIM_OFF);
  angle_changed = 1;
}
