// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: UART_TFT_ESP32

#include "ui.h"
int led_color = 0;

void LED_CTRL(lv_event_t * e)
{
	led_color = 1;
}
