// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Servo_Control

#include "ui.h"

void Slider_Angle(lv_event_t * e)
{
	// Your code here
}

void Arc_Angle(lv_event_t * e)
{
	// Your code here
}
