// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp_and_Humi_Chart = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_temp_and_Humi_Chart, 247);
    lv_obj_set_height(ui_temp_and_Humi_Chart, 175);
    lv_obj_set_x(ui_temp_and_Humi_Chart, 2);
    lv_obj_set_y(ui_temp_and_Humi_Chart, 1);
    lv_obj_set_align(ui_temp_and_Humi_Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_temp_and_Humi_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_temp_and_Humi_Chart, 14);
    lv_chart_set_div_line_count(ui_temp_and_Humi_Chart, 25, 22);
    lv_chart_set_axis_tick(ui_temp_and_Humi_Chart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_temp_and_Humi_Chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 13, 2, true, 50);
    lv_chart_set_axis_tick(ui_temp_and_Humi_Chart, LV_CHART_AXIS_SECONDARY_Y, 8, 5, 11, 2, true, 25);
    lv_chart_series_t * ui_temp_and_Humi_Chart_series_1 = lv_chart_add_series(ui_temp_and_Humi_Chart,
                                                                              lv_color_hex(0xFF0000), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_temp_and_Humi_Chart_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_temp_and_Humi_Chart, ui_temp_and_Humi_Chart_series_1,
                             ui_temp_and_Humi_Chart_series_1_array);
    lv_chart_series_t * ui_temp_and_Humi_Chart_series_2 = lv_chart_add_series(ui_temp_and_Humi_Chart,
                                                                              lv_color_hex(0x1100FF), LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_temp_and_Humi_Chart_series_2_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_temp_and_Humi_Chart, ui_temp_and_Humi_Chart_series_2,
                             ui_temp_and_Humi_Chart_series_2_array);



    ui_temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, -73);
    lv_obj_set_y(ui_temp, -96);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "Temperature:");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Humi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humi, 78);
    lv_obj_set_y(ui_Humi, -97);
    lv_obj_set_align(ui_Humi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humi, "Humidity:");
    lv_obj_set_style_text_color(ui_Humi, lv_color_hex(0x1000FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humi, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}
