// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Lamp_Display_ctrl

#ifndef _LAMP_DISPLAY_CTRL_UI_H
#define _LAMP_DISPLAY_CTRL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LAMP;
void ui_event_ButtonON(lv_event_t * e);
extern lv_obj_t * ui_ButtonON;
extern lv_obj_t * ui_Label1;
void ui_event_ButtonOFF(lv_event_t * e);
extern lv_obj_t * ui_ButtonOFF;
extern lv_obj_t * ui_OFF;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_394551424);    // assets/lamp-svg.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
