// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Lamp_Display_ctrl

#include "ui.h"
#include <Arduino.h>

void ON_LAMP(lv_event_t * e)
{
	digitalWrite(22, HIGH);
}

void OFF_LAMP(lv_event_t * e)
{
	digitalWrite(22, LOW);
}
