// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Lamp_Display_ctrl

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ON_LAMP(lv_event_t * e);
void OFF_LAMP(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
