// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Lamp_Display_ctrl

#include "ui.h"

void ON_LAMP(lv_event_t * e)
{
	// Your code here
}

void OFF_LAMP(lv_event_t * e)
{
	// Your code here
}
