// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Speed

#ifndef _SPEED_UI_H
#define _SPEED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void Compassmove_Animation(lv_obj_t * TargetObject, int delay);
void CompassMove2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Overlay;
extern lv_obj_t * ui_guage;
extern lv_obj_t * ui_guage_overlay;
extern lv_obj_t * ui_guage_number;
void ui_event_speed_slide(lv_event_t * e);
extern lv_obj_t * ui_speed_slide;
extern lv_obj_t * ui_Car_Range_;
void ui_event_Car_Slide(lv_event_t * e);
extern lv_obj_t * ui_Car_Slide;
extern lv_obj_t * ui_compass_layout;
extern lv_obj_t * ui_compass;
extern lv_obj_t * ui_Battery_layout;
extern lv_obj_t * ui_Battery_Bar;
extern lv_obj_t * ui_speed_type_panel;
extern lv_obj_t * ui_speed_type_txt;
extern lv_obj_t * ui_battery_percent;
extern lv_obj_t * ui_speed_label;
extern lv_obj_t * ui_Km_per_hour_label;
extern lv_obj_t * ui_range_txt;
extern lv_obj_t * ui_range_num;
extern lv_obj_t * ui_Trip_txt;
void ui_event_compass_check_fwd(lv_event_t * e);
extern lv_obj_t * ui_compass_check_fwd;
void ui_event_compass_check_Rev(lv_event_t * e);
extern lv_obj_t * ui_compass_check_Rev;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_devider_png);    // assets/devider.png
LV_IMG_DECLARE(ui_img_guage_bg_png);    // assets/guage bg.png
LV_IMG_DECLARE(ui_img_1449175297);    // assets/guage bg (1).png
LV_IMG_DECLARE(ui_img_guage_bg_1_png);    // assets/guage bg_1.png
LV_IMG_DECLARE(ui_img_guage_indicator_png);    // assets/guage indicator.png
LV_IMG_DECLARE(ui_img_range_bg_png);    // assets/range bg.png
LV_IMG_DECLARE(ui_img_range_knob_png);    // assets/range knob.png
LV_IMG_DECLARE(ui_img_compass_overlay_png);    // assets/compass overlay.png
LV_IMG_DECLARE(ui_img_compas_png);    // assets/compas.png
LV_IMG_DECLARE(ui_img_battery_bg_png);    // assets/battery bg.png
LV_IMG_DECLARE(ui_img_battery_indicator_png);    // assets/battery indicator.png



LV_FONT_DECLARE(ui_font_SF_Sports_Night_BIg);
LV_FONT_DECLARE(ui_font_SF_Sports_Night_Medium);
LV_FONT_DECLARE(ui_font_SF_Sports_Night_Small);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
